# Generated by Django 5.1.7 on 2025-03-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='description',
        ),
        migrations.AddField(
            model_name='loans',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
